### ISSUE TITLE
Logout does not work

### ISSUE THREAD

**Issue by ramstein74** [ueberauth/ueberauth_example#12]
Hello i´m just testing the identity.I deleted all but except identity.

However the logout is not working...
IT does nothing and the cookie is still set

can you help?

**Comment by doomspork** [comment]
Hi @ramstein74, sorry for the late response.  Are you still having this issue?  Can you reproduce it on master?

**Comment by emoragaf** [comment]
I was having the same problem, changed `<%= link "logout"` for `<%= button "Logout"` and it works for me now.

I don't know if there's a issue using the link helper with :delete method.

**Comment by doomspork** [comment]
@emoragaf a PR including your fix would be welcomed if you're interested :grinning:
