### ISSUE TITLE
Application error

### ISSUE THREAD

**Issue by Valentin-Seehausen** [ueberauth/ueberauth_example#13]
http://ueberauth-example.herokuapp.com/

**Comment by doomspork** [comment]
Hi @Valentin-Seehausen, we just noticed this ourselves.  

The application runs fine locally but crashes on Heroku. :disappointed:   I'm going to look into what's going on with this today.

**Comment by doomspork** [comment]
This has been resolved now @Valentin-Seehausen, thanks!
