### ISSUE TITLE
Github not working with other apps?

### ISSUE THREAD

**Issue by corroded** [ueberauth/ueberauth_example#23]
Hi, I am failry new to Elixir and Phoenix and am just following guides etc and I got a Github auth to actually work in my local. I then checked and tested https://ueberauth-example.herokuapp.com/ and every other link works except Github, which gives me a `failed to authenticate` error (see  screenshot)
![screen shot 2016-08-24 at 9 05 30 am](https://cloud.githubusercontent.com/assets/46548/17915058/f6ea2672-69d9-11e6-993a-0de9bc1e3e13.png)

I noticed though that it works again if I use an incognito window. Not sure if this is a legit issue but does that mean I can only have one app running that uses uberauth / github? Or am I doing something wrong here?

As additional info, I have a sample app that closely follows https://github.com/ueberauth/ueberauth_github. I've set it up in Github to point to localhost and it actually works:

![screen shot 2016-08-24 at 9 08 37 am](https://cloud.githubusercontent.com/assets/46548/17915117/770e4068-69da-11e6-9c05-6894ce9c633d.png)

**Comment by doomspork** [comment]
Thanks for the heads up @corroded, I'm going to assume this is a bug until we understand it more.

**Comment by DarkMarmot** [comment]
This still seems to be happening? Any chance of fixing this one?

**Comment by doomspork** [comment]
@DarkMarmot have you run this locally with your own credentials and verified it's an issue?

**Comment by tajchumber** [comment]
closing this as it's solved with https://github.com/ueberauth/ueberauth_example/pull/60
can reopen if the issue still persists
