### ISSUE TITLE
Strange error with brunch

### ISSUE THREAD

**Issue by sobolevn** [ueberauth/ueberauth_example#31]
I have never actually seen something like this.

> [info] Running UeberauthExample.Endpoint with Cowboy using http://localhost:4000
> 
> 
> #
> # Fatal error in ../deps/v8/src/api.cc, line 1062
> # Check failed: !value_obj->IsJSReceiver() || value_obj->IsTemplateInfo().
> #
> 
> ==== C stack trace ===============================
> 
>     0   node                                0x00000001008c6d19 v8::base::debug::StackTrace::StackTrace() + 19
>     1   node                                0x00000001008c5a31 V8_Fatal + 233
>     2   node                                0x0000000100146038 v8::Template::SetAccessorProperty(v8::Local<v8::Name>, v8::Local<v8::FunctionTemplate>, v8::Local<v8::FunctionTemplate>, v8::PropertyAttribute, v8::AccessControl) + 0
>     3   fse.node                            0x00000001044e6bb1 fse::FSEvents::Initialize(v8::Local<v8::Object>) + 197
>     4   node                                0x00000001007c6ed3 node::DLOpen(v8::FunctionCallbackInfo<v8::Value> const&) + 860
>     5   node                                0x000000010016a408 v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) + 340
>     6   node                                0x00000001001b1bdf v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) + 915
>     7   node                                0x00000001001b11b9 v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*) + 281
>     8   ???                                 0x00001622ca2843a7 0x0 + 24338676335527
> 
> 

## Steps to reproduce

1. `clone master`
2. `mix deps.get && npm install`
3. `export SECRET_KEY_BASE=$(mix phoenix.gen.secret)`
4. `mix phoenix.server`

## My setup

Elixir

> » elixir --version
> Erlang/OTP 19 [erts-8.2.2] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]
> 
> Elixir 1.4.2

node

> » node --version
> v7.9.0

npm

> » npm --version
> 4.2.0

os

> » uname -a
> Darwin Mackbook-Nikita 15.6.0 Darwin Kernel Version 15.6.0: Fri Feb 17 10:21:18 PST 2017; root:xnu-3248.60.11.4.1~1/RELEASE_X86_64 x86_64

**Comment by International** [comment]
I encountered the same. If I open the browser, I also see this:
<pre>
** (UndefinedFunctionError) function :crypto.rand_bytes/1 is undefined or private. Did you mean one of:

      * rand_seed/0
      * rand_seed/1

    :crypto.rand_bytes(20)
</pre>

and it originates from <b>plug/lib/plug/request_id.ex</b>. Specifically this:
```
  defp generate_request_id do
    :crypto.rand_bytes(20) |> Base.hex_encode32(case: :lower)
  end
```

If I change `rand_bytes` to `strong_rand_bytes`, I still get the JS error in the console, but the app seems to function despite that.

**Comment by doomspork** [comment]
After we get Guardian v1 out I would like to shift focus to giving Ueberauth and strategies some much needed TLC.  As part of that I'd like to brainstorm a better example project that will encompass a number of different scenarios.

I would absolutely positively love to get users of these packages involved in building something that can serve as a useful example to others.

**Comment by chulkilee** [comment]
This can be closed, since the problematic elixir/erlang versions (elixir 1.4.2 and otp 19) are no longer supported: https://hexdocs.pm/elixir/compatibility-and-deprecations.html
