### ISSUE TITLE
Update the project to Phoenix 1.13

### ISSUE THREAD

**Issue by rishavs** [ueberauth/ueberauth_example#35]
Can we please update the project to the latest Phoenix (and other dependency) versions?
For someone who is completely new to Phoenix, the older versions can be confusing.

**Comment by doomspork** [comment]
Howdy!  Updating this is a little low on the list of priorities for the contributors at the moment.  We're busy working on Guardian v1 so we can shift our focus to giving Ueberauth (and the strategies) some much needed TLC.

That said @rishavs, pull requests are always welcome!  A great way to learn how to use Ueberauth is to give it a shot 😁

**Comment by rishavs** [comment]
Thanks for replying. I am currently trying to get this to work on 1.1.3 but having a weird error
````
=INFO REPORT==== 4-Aug-2017::02:33:51 ===
    application: logger
    exited: stopped
    type: temporary
** (Mix) Could not start application oauth: could not find application file: oauth.app
````
i havent written the auth controller code so that might be an issue. but i have not used oauth2 anywhere so far manually (i guess it comes as a dependency for some of the strategies)

**Comment by doomspork** [comment]
Howdy @rishavs!  Do you have this code up on a public repo?

**Comment by zacck** [comment]
@doomspork  I'm keen to do this if it's still on the table

**Comment by doomspork** [comment]
@zacck please do!  I'm happy to help in a limited capacity 👍

**Comment by zacck** [comment]
@doomspork  I think the PR for this is done and pushed
