### ISSUE TITLE
Fails with current version of Python

### ISSUE THREAD

**Issue by PeterDavidCarter** [ueberauth/ueberauth_example#38]
Error

```
gyp ERR! configure error 
gyp ERR! stack Error: Python executable "/Users/user/anaconda3/bin/python" is v3.6.3, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
```

Relies on end-user having an alternative Python installation and knowing the installation directory. Please update to work with current Python version.

**Comment by doomspork** [comment]
@PeterDavidCarter this project doesn't rely on Python, are you sure you have the correct project?

**Comment by sibagithub** [comment]
I am also getting this error in MAC because of Python installed with Anaconda package.

**Comment by doomspork** [comment]
@sibagithub and @PeterDavidCarter are you both sure you're using the correct packages?  This is an Elixir project and should not have any Python dependencies.

Could you kindly provide me the series of commands you're attempt to run?

**Comment by sibagithub** [comment]
Sorry for any confusion.

I was trying to install Google cloud offline emulator and got the message.
