### ISSUE TITLE
twitter heroku login not working

### ISSUE THREAD

**Issue by hassox** [ueberauth/ueberauth_example#4]
When I click on the twitter auth I land on an error page :(

**Comment by doomspork** [comment]
Sorry I mentioned yesterday on Slack I was getting an error.  Something came up in the evening and I didn't get to finish.  I'll look at it today.

**Comment by doomspork** [comment]
This is fixed :+1:

**Comment by doomspork** [comment]
I removed Twitter from the current deployed version, I'm still working on that strategy.

**Comment by doomspork** [comment]
This issue is old so I'm closing.  Twitter is integrated and working.
