### ISSUE TITLE
Error with Elixir 1.8

### ISSUE THREAD

**Issue by norpan** [ueberauth/ueberauth_example#43]
Running this with Elixir 1.8 I get the following error:
```
== Compilation error in file lib/ueberauth_example_web/views/auth_view.ex ==
** (BadMapError) expected a map, got: {:safe, ""}
    (eex) lib/eex/engine.ex:161: EEx.Engine.handle_begin/1
    (eex) lib/eex/compiler.ex:54: EEx.Compiler.generate_buffer/4
    (phoenix) lib/phoenix/template.ex:378: Phoenix.Template.compile/2
    (phoenix) lib/phoenix/template.ex:186: anonymous fn/3 in Phoenix.Template."MACRO-__before_compile__"/2
    (elixir) lib/enum.ex:1940: Enum."-reduce/3-lists^foldl/2-0-"/3
    (phoenix) expanding macro: Phoenix.Template.__before_compile__/1
    lib/ueberauth_example_web/views/auth_view.ex:1: UeberauthExampleWeb.AuthView (module)
    (elixir) lib/kernel/parallel_compiler.ex:208: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/6
```

**Comment by doomspork** [comment]
@norpan this example app needs a facelift to be brought up to speed with Ueberauth, Elixir, and Phoenix.

Do you have any interest in helping out? We could definitely use some extra hands 😁

**Comment by norpan** [comment]
I would love to help, but I haven't really got a good grasp of Phoenix and EEx

**Comment by axelson** [comment]
@okadath if you use Elixir 1.7.4 or lower than you will be able to run without issue. Or you can try my PR: https://github.com/ueberauth/ueberauth_example/pull/44 cc: @norpan

**Comment by okadath** [comment]
> @okadath if you use Elixir 1.7.4 or lower than you will be able to run without issue. Or you can try my PR: #44 cc: @norpan

TY!!!!!
