### ISSUE TITLE
Why do we use Oauth library?

### ISSUE THREAD

**Issue by shijithkjayan** [ueberauth/ueberauth_example#47]
This is not a bug, its actually a doubt of mine. Why do we use the erlang library [oauth](https://github.com/tim/erlang-oauth)  when the [ueberauth repo](https://github.com/ueberauth/ueberauth) doesn't ask us to add the erlang library in its documentation.

**Comment by yordis** [comment]
From that repo

> This implementation should be compatible with the signature algorithms presented in RFC5849 - The OAuth 1.0 Protocol, and OAuth Core 1.0 Revision A. It is not intended to cover OAuth 2.0.

That means that only Twitter provider will probably use this package.

Also, OAuth should be hidden from you unless you are creating a new provider.

**Comment by yordis** [comment]
@shijithkjayan maybe because of Twitter strategy 🤔 

In any case, please use the Slack channel or Elixir forum for this, you will probably get faster and better responses.
