### ISSUE TITLE
Logout doesn't work

### ISSUE THREAD

**Issue by RobertLowe** [ueberauth/ueberauth_example#49]
Steps to reproduce:

1. Go to the demo app: http://ueberauth-example.herokuapp.com/
2. Create a account via email/password
3. Click logout

Nothing happens.

Relates to #12 ?

**Comment by wayferer** [comment]
I tried out the suggested solution in #12 but it doesn't seem to be enough on it's own as the user doesn't seem to be logged out or the session isn't being dropped.

**Comment by ramortegui** [comment]
@doomspork , @yordis , Is there a chance to re-deploy the app on Heroku to verify that this issue was solved by https://github.com/ueberauth/ueberauth_example/pull/54 ?

**Comment by doomspork** [comment]
@ramortegui deploying now and fixed the automatic deploys as well :+1: 

Thanks again for all your help! I'm open to suggestions on improving the app and I'm happy to help as I can in doing so.
