### ISSUE TITLE
@current_user.name is nil for Google Authentication

### ISSUE THREAD

**Issue by bezborodow** [ueberauth/ueberauth_example#50]
Using the example app, I tried authenticating with Google, the `@current_user.id` and `@current_user.avatar` is set but `@current_user.avatar` is nil. It is the same in my own application as well.

**Comment by bezborodow** [comment]
I managed to fix this by adding `default_scope: "email profile"` in `config/config.exs` as follows:

```
# Überauth
config :ueberauth, Ueberauth,
  providers: [
    google: {Ueberauth.Strategy.Google, [
      default_scope: "email profile",
      ...............
    ]}  
  ]
```

**Comment by doomspork** [comment]
@bezborodow would you be willing to open a PR to update this project's configuration and perhaps add a note to the README here and `ueberauth_google` if it's not already mentioned?
