### ISSUE TITLE
Github Actions Failing

### ISSUE THREAD

**Issue by ramortegui** [ueberauth/ueberauth_example#58]
Github actions fails as per issues with DB credentials, and It was fixed as part of https://github.com/ueberauth/ueberauth_example/pull/54 PR.

```
19:38:19.906 [error] GenServer #PID<0.3995.0> terminating
** (Postgrex.Error) FATAL 28000 (invalid_authorization_specification): role "runner" does not exist
    (db_connection) lib/db_connection/connection.ex:163: DBConnection.Connection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: nil
** (Mix) The database for UeberauthExample.Repo couldn't be created: FATAL 28000 (invalid_authorization_specification): role "runner" does not exist
##[error]Process completed with exit code 1.
```

**Comment by ramortegui** [comment]
Solved in https://github.com/ueberauth/ueberauth_example/pull/54

**Comment by doomspork** [comment]
@ramortegui you're so awesome! Thank you for getting involved. We'd love to see what future contributions you have in store.

If you're interested in getting more involved in Ueberauth I'd be happy to talk to you more about doing so.

**Comment by ramortegui** [comment]
Hey @doomspork, glad to help.  Yes, I'd love to contribute and be more involved in Ueberauth.  If you have something in mind, please let me know! 😃

**Comment by ilovemysillybanana** [comment]
It’s actually still failing on the live heroku version
