### ISSUE TITLE
Missing step in README.md

### ISSUE THREAD

**Issue by wribln** [ueberauth/ueberauth_example#69]
When attempting to run the sample code, there needs to be a 'mix ecto.create' step before attempting to start the phx.server. I don't understand why as the sample code does not seem to make use of a database. I am not sure if this is a missing piece of documentation or a piece of code needing adjustment.

**Comment by Hanspagh** [comment]
Hi @wribln 
This code is based on a basic phoenix example and therefore also starts an ecto Repo. Hence the need for `ecto.create`. You are right this is not used for anything at the moment. Feel free to add a pr either removing ecto or updating the docs. Hope this makes senes.

**Comment by wribln** [comment]
Hey, @Hanspagh 
thank you for your quick response. I think the ecto repo should be removed so people are not confused - but I am not sure if I am able to create a correct pr at this time (just learning Phoenix/Elixir/Ecto/...). If you can give me an easy hint, I will try. BR

**Comment by Hanspagh** [comment]
I think it might make sense to reduce the complexity.

- The first thing you could do is remove it from the application [here](https://github.com/ueberauth/ueberauth_example/blob/master/lib/ueberauth_example/application.ex) This will make sure ecto is not started, but it might interfere with some of the test setup, but you whould be able to start the app.
- After this, you can remove ecto as a dependency 
- And then you would need to clean up some of the tests configs that still would point at some ecto stuff.
Hope this helps

**Comment by wribln** [comment]
PR #70 created.

**Comment by wribln** [comment]
PR merged.
