### ISSUE TITLE
URL to clone repo in README.md didn't work for me.

### ISSUE THREAD

**Issue by rerb** [ueberauth/ueberauth_example#81]
The URL in the "Clone the project" section of README.md, 
  - `git@github.com:ueberauth/ueberauth_example.git`
 
didn't work for me. 

The errors were; 
  - `git@github.com: Permission denied (publickey).`
  - `fatal: Could not read from remote repository.`

The following URL works
  - https://github.com/ueberauth/ueberauth_example.git

Aw, man, that's simple enough for me to fix.  PR coming.

**Comment by yordis** [comment]
The issue is that you didn't add your SSK to GitHub, but I think it is worth changing it anyway
